
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ACLC PC17
 */
public class ManageCategory extends javax.swing.JFrame {

    private int categoryPk = 0;
    private String category_pk;

    /**
     * Creates new form ManageCategory
     */
    public ManageCategory() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private boolean validateFields() {
        if (!txtname.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    private void formComponentShown(java.awt.event.ComponentEvent evt) {

        DefaultTableModel model = (DefaultTableModel) tableCategory.getModel();

        try {
//          Connection con = ConnectionProvider.getCon();
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
            ps = con.prepareStatement("Select * from inventorymanagementsystem where userrole = ?");
            ps.executeQuery("Select * from category");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("category_pk"), rs.getString("name")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtname = new javax.swing.JTextField();
        searchbar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCategory = new javax.swing.JTable();
        update = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        save = new javax.swing.JButton();
        close = new javax.swing.JButton();
        BG5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(876, 540));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(41, 88, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE CATEGORY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 60));

        jPanel6.setBackground(new java.awt.Color(163, 198, 134));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(41, 88, 82));
        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 30, 40));

        jPanel7.setBackground(new java.awt.Color(163, 198, 134));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(41, 88, 82));
        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, 10));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 880, 60);

        txtname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 88, 82), 2, true));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(460, 80, 380, 30);

        searchbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchbarKeyTyped(evt);
            }
        });
        getContentPane().add(searchbar);
        searchbar.setBounds(81, 80, 310, 30);

        tableCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 186, 24)));
        tableCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableCategory.setForeground(new java.awt.Color(41, 88, 82));
        tableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        tableCategory.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tableCategory.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tableCategory);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 120, 800, 360);

        update.setBackground(new java.awt.Color(0, 29, 29));
        update.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(242, 242, 242));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(290, 490, 100, 30);

        jPanel2.setBackground(new java.awt.Color(163, 198, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/magnifying-glass.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 30, 30));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 29, 29));
        jLabel2.setText("NAME:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 60, 30));

        jPanel3.setBackground(new java.awt.Color(41, 88, 82));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 880, -1));

        jPanel4.setBackground(new java.awt.Color(41, 88, 82));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 10, 440));

        jPanel5.setBackground(new java.awt.Color(41, 88, 82));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 10, 440));

        refresh.setBackground(new java.awt.Color(0, 29, 29));
        refresh.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        refresh.setForeground(new java.awt.Color(242, 242, 242));
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 100, -1));

        save.setBackground(new java.awt.Color(0, 29, 29));
        save.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        save.setForeground(new java.awt.Color(242, 242, 242));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 100, -1));

        close.setBackground(new java.awt.Color(0, 29, 29));
        close.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(242, 242, 242));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 110, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 880, 540);

        BG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/mrr.png"))); // NOI18N
        BG5.setMaximumSize(new java.awt.Dimension(876, 540));
        BG5.setMinimumSize(new java.awt.Dimension(876, 540));
        BG5.setPreferredSize(new java.awt.Dimension(876, 540));
        getContentPane().add(BG5);
        BG5.setBounds(0, 0, 876, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String name = txtname.getText();
        if (validateFields()) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                // MySQL Connector
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");

                // Specify that we want to retrieve generated keys (ID)
                ps = con.prepareStatement(
                        "insert into category (name) values (?)",
                        Statement.RETURN_GENERATED_KEYS
                );
                ps.setString(1, name);

                // Execute the insert
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Category Added Successfully!");

                // Retrieve the generated keys (auto-incremented ID)
                ResultSet rs = ps.getGeneratedKeys();
                if (rs.next()) {
                    int newCategoryID = rs.getInt(1); // Get the auto-generated ID

                    DefaultTableModel model = (DefaultTableModel) tableCategory.getModel();
                    model.addRow(new Object[]{
                        newCategoryID, // Auto-generated ID
                        txtname.getText() // Name of the category
                    });
                }
                setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         try {
            int selectedRow = tableCategory.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Please select a category to update.");
                return;
            }

            // Get the ID of the selected user (from the table)
            String categoryId = tableCategory.getValueAt(selectedRow, 0).toString(); 
            String name = txtname.getText();
           
            // Validate fields
            if (validateFields()) {
                JOptionPane.showMessageDialog(null, "All fields are required.");
            } else {
                // Connect to the database
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
                ps = con.prepareStatement(
                        "UPDATE category SET name = ? WHERE category_pk = ?"
                );
            
                       
                ps.setString(1, name);          
                ps.setString(2, categoryId);         

                // Execute update
                int rowsUpdated = ps.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Category updated successfully!");
                    // Update the table row with the new values
                    
                    tableCategory.setValueAt(name, selectedRow, 1);
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Category update failed.");
                }
            }
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableCategory.getModel();
    model.setRowCount(0); // Clear the table

    try {
        // Database connection
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");

        // Query to fetch all categories
        String query = "SELECT * FROM category";
        ps = con.prepareStatement(query);
        rs = ps.executeQuery();

        // Add each row to the table
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("category_pk"), // Replace with actual column names
                rs.getString("name")
            });
        }
    } catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, "Error fetching categories: " + e.getMessage());
    }
    }//GEN-LAST:event_refreshActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the app?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            this.dispose();
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void searchbarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyTyped
        // TODO add your handling code here:
        try {
            // Mysql Connector
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
            String query = "SELECT * FROM category WHERE category_pk LIKE ? OR name LIKE ?";

            ps = con.prepareStatement(query);
            String searchText = "%" + searchbar.getText() + "%";

            ps.setString(1, searchText);
            ps.setString(2, searchText);
           
           

            rs = ps.executeQuery();
            DefaultTableModel dt = (DefaultTableModel) tableCategory.getModel();
            dt.setRowCount(0);

            while (rs.next()) {
                dt.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2)
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManageCategory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchbarKeyTyped

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tableCategory.getModel();
        model.setRowCount(0);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");

            ResultSet rs = ps.executeQuery();

            // Loop through the result set and add each product to the table
            while (rs.next()) {
                String id = rs.getString("category_pk");
                String named = rs.getString("name");
                
               

                // Add row to the table
                model.addRow(new Object[]{id, txtname});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to search products: " + e.getMessage());
        }
    }//GEN-LAST:event_searchbarActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG5;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTextField searchbar;
    private javax.swing.JTable tableCategory;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
